CREATE TABLE WORDS (
WORD_ID NUMBER PRIMARY KEY, 
WORD VARCHAR2(30 CHAR) NOT NULL, 
CATEGORY VARCHAR2(15 CHAR)
);


CREATE TABLE HANGED_MAN(	
HANGED_MAN_ID NUMBER(2,0) NOT NULL, 
HANGED_MAN VARCHAR2(4000 BYTE) NOT NULL
);


CREATE TABLE RANKINGS (	
USERNAME VARCHAR2(30 CHAR), 
WORD_ID NUMBER, 
PROGRESS VARCHAR2(30 CHAR), 
CATEGORY VARCHAR2(15 CHAR), 
DAYS DATE, 
ATTEMPTS NUMBER, 
DURATION INTERVAL DAY (0) TO SECOND (0), 
RESULTS VARCHAR2(5 BYTE), 
MISTAKES NUMBER
);


CREATE TABLE GAME_SESSIONS (
USERNAME VARCHAR2(100 BYTE) PRIMARY KEY, 
WORD_ID NUMBER(4,0), 
WORD VARCHAR2(30 CHAR), 
MASKED_WORD VARCHAR2(30 CHAR), 
MISTAKES_COUNT NUMBER(2,0), 
ATTEMPTS_COUNT NUMBER(2,0), 
CATEGORY VARCHAR2(15 CHAR), 
HANGED_MAN VARCHAR2(4000 BYTE), 
START_TIME TIMESTAMP, 
LETTERS VARCHAR2(100 CHAR) 
);

CREATE OR REPLACE VIEW RESULTS AS
SELECT 
R.USERNAME AS USERS, 
H.WORD AS WORDS ,
R.PROGRESS AS PROGRESS ,
R.CATEGORY AS CATEGORIES
, R.DAYS AS DATES, 
R.RESULTS AS RESULTS, 
R.ATTEMPTS AS NUMBER_OF_ATTEMPTS ,
R.MISTAKES AS NUMBER_OF_MISTAKES,
EXTRACT(MINUTE FROM R.DURATION)||':'||EXTRACT(SECOND FROM R.DURATION) AS DURATIONS 
FROM RANKINGS R
JOIN WORDS H
ON H.WORD_ID=R.WORD_ID;

-- WORDS
Insert into WORDS (WORD_ID,WORD,CATEGORY) values (1,'FORGET-ME-NOT','NATURE');
Insert into WORDS (WORD_ID,WORD,CATEGORY) values (2,'METALLICA','CULTURE');
Insert into WORDS (WORD_ID,WORD,CATEGORY) values (3,'KOPERNIK','PERSON');
Insert into WORDS (WORD_ID,WORD,CATEGORY) values (4,'INCREDULOUSNESS','NOUN');
Insert into WORDS (WORD_ID,WORD,CATEGORY) values (5,'PITTSBURGH','GEOGRAPHY');
Insert into WORDS (WORD_ID,WORD,CATEGORY) values (6,'EXPECTATION','NOUN');
Insert into WORDS (WORD_ID,WORD,CATEGORY) values (7,'VAGABOND','NOUN');
Insert into WORDS (WORD_ID,WORD,CATEGORY) values (8,'QOMOLANGMA','GEOGRAPHY');



-- HANGED_MAN
Insert into  HANGED_MAN (HANGED_MAN_ID,HANGED_MAN) values (0,' 
');

Insert into  HANGED_MAN (HANGED_MAN_ID,HANGED_MAN) values (1,'



|
|
|
');
Insert into  HANGED_MAN (HANGED_MAN_ID,HANGED_MAN) values (2,'

|    
|    
|   
|   
|
');
Insert into  HANGED_MAN (HANGED_MAN_ID,HANGED_MAN) values (3,'
_____
|    
|    
|   
|   
|
');
Insert into  HANGED_MAN (HANGED_MAN_ID,HANGED_MAN) values (4,'
_____
|    |
|    
|   
|   
|
');
Insert into  HANGED_MAN (HANGED_MAN_ID,HANGED_MAN) values (5,'
_____
|    |
|    o
|   
|   
|
');
Insert into  HANGED_MAN (HANGED_MAN_ID,HANGED_MAN) values (6,'
_____
|    |
|    o
|    |
|   
|
');
Insert into  HANGED_MAN (HANGED_MAN_ID,HANGED_MAN) values (7,'
_____
|    |
|    o
|   /|
|   
|
');
Insert into  HANGED_MAN (HANGED_MAN_ID,HANGED_MAN) values (8,'
_____
|    |
|    o
|   /|\
|   
|
');
Insert into  HANGED_MAN (HANGED_MAN_ID,HANGED_MAN) values (9,'
_____
|    |
|    o
|   /|\
|   /*\
|
');

Insert into  HANGED_MAN (HANGED_MAN_ID,HANGED_MAN) values (99,'
\o/
 |
/*\
');
COMMIT;